// AUTO-GENERATED by scripts/gen-teams.mjs — do not edit by hand.
// RU↔EN team map (from "Справочник") + flag codes (from generate.mjs).
// canon()/ALIASES mirror the Apps Script that fills the sheet, so the site and
// the sheet resolve API-Football names identically.

export type TeamInfo = { en: string; flag: string; group: string };

export const TEAMS: Record<string, TeamInfo> = {
  "Австралия": {
    "en": "Australia",
    "flag": "au",
    "group": "D"
  },
  "Австрия": {
    "en": "Austria",
    "flag": "at",
    "group": "J"
  },
  "Алжир": {
    "en": "Algeria",
    "flag": "dz",
    "group": "J"
  },
  "Англия": {
    "en": "England",
    "flag": "gb-eng",
    "group": "L"
  },
  "Аргентина": {
    "en": "Argentina",
    "flag": "ar",
    "group": "J"
  },
  "Бельгия": {
    "en": "Belgium",
    "flag": "be",
    "group": "G"
  },
  "Босния и Гер.": {
    "en": "Bosnia and Herzegovina",
    "flag": "ba",
    "group": "B"
  },
  "Бразилия": {
    "en": "Brazil",
    "flag": "br",
    "group": "C"
  },
  "Гаити": {
    "en": "Haiti",
    "flag": "ht",
    "group": "C"
  },
  "Гана": {
    "en": "Ghana",
    "flag": "gh",
    "group": "L"
  },
  "Германия": {
    "en": "Germany",
    "flag": "de",
    "group": "E"
  },
  "ДР Конго": {
    "en": "Congo DR",
    "flag": "cd",
    "group": "K"
  },
  "Египет": {
    "en": "Egypt",
    "flag": "eg",
    "group": "G"
  },
  "Иордания": {
    "en": "Jordan",
    "flag": "jo",
    "group": "J"
  },
  "Ирак": {
    "en": "Iraq",
    "flag": "iq",
    "group": "I"
  },
  "Иран": {
    "en": "Iran",
    "flag": "ir",
    "group": "G"
  },
  "Испания": {
    "en": "Spain",
    "flag": "es",
    "group": "H"
  },
  "Кабо-Верде": {
    "en": "Cape Verde Islands",
    "flag": "cv",
    "group": "H"
  },
  "Канада": {
    "en": "Canada",
    "flag": "ca",
    "group": "B"
  },
  "Катар": {
    "en": "Qatar",
    "flag": "qa",
    "group": "B"
  },
  "Колумбия": {
    "en": "Colombia",
    "flag": "co",
    "group": "K"
  },
  "Кот-д'Ивуар": {
    "en": "Ivory Coast",
    "flag": "ci",
    "group": "E"
  },
  "Кюрасао": {
    "en": "Curacao",
    "flag": "cw",
    "group": "E"
  },
  "Марокко": {
    "en": "Morocco",
    "flag": "ma",
    "group": "C"
  },
  "Мексика": {
    "en": "Mexico",
    "flag": "mx",
    "group": "A"
  },
  "Нидерланды": {
    "en": "Netherlands",
    "flag": "nl",
    "group": "F"
  },
  "Новая Зеландия": {
    "en": "New Zealand",
    "flag": "nz",
    "group": "G"
  },
  "Норвегия": {
    "en": "Norway",
    "flag": "no",
    "group": "I"
  },
  "Панама": {
    "en": "Panama",
    "flag": "pa",
    "group": "L"
  },
  "Парагвай": {
    "en": "Paraguay",
    "flag": "py",
    "group": "D"
  },
  "Португалия": {
    "en": "Portugal",
    "flag": "pt",
    "group": "K"
  },
  "С.Аравия": {
    "en": "Saudi Arabia",
    "flag": "sa",
    "group": "H"
  },
  "США": {
    "en": "USA",
    "flag": "us",
    "group": "D"
  },
  "Сенегал": {
    "en": "Senegal",
    "flag": "sn",
    "group": "I"
  },
  "Тунис": {
    "en": "Tunisia",
    "flag": "tn",
    "group": "F"
  },
  "Турция": {
    "en": "Turkey",
    "flag": "tr",
    "group": "D"
  },
  "Узбекистан": {
    "en": "Uzbekistan",
    "flag": "uz",
    "group": "K"
  },
  "Уругвай": {
    "en": "Uruguay",
    "flag": "uy",
    "group": "H"
  },
  "Франция": {
    "en": "France",
    "flag": "fr",
    "group": "I"
  },
  "Хорватия": {
    "en": "Croatia",
    "flag": "hr",
    "group": "L"
  },
  "Чехия": {
    "en": "Czech Republic",
    "flag": "cz",
    "group": "A"
  },
  "Швейцария": {
    "en": "Switzerland",
    "flag": "ch",
    "group": "B"
  },
  "Швеция": {
    "en": "Sweden",
    "flag": "se",
    "group": "F"
  },
  "Шотландия": {
    "en": "Scotland",
    "flag": "gb-sct",
    "group": "C"
  },
  "Эквадор": {
    "en": "Ecuador",
    "flag": "ec",
    "group": "E"
  },
  "Ю.Корея": {
    "en": "South Korea",
    "flag": "kr",
    "group": "A"
  },
  "ЮАР": {
    "en": "South Africa",
    "flag": "za",
    "group": "A"
  },
  "Япония": {
    "en": "Japan",
    "flag": "jp",
    "group": "F"
  }
};

// API-Football spelling variants → canonical normalized form
const ALIASES: Record<string, string> = {
  turkiye: "turkey",
  czechia: "czechrepublic",
  korearepublic: "southkorea",
  capeverde: "capeverdeislands",
  drcongo: "congodr",
  congodemocraticrepublic: "congodr",
  bosniaherzegovina: "bosniaandherzegovina",
  cotedivoire: "ivorycoast",
  unitedstates: "usa",
};

export function norm(s: string): string {
  return String(s || "").toLowerCase()
    .normalize("NFD").replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]/g, "");
}
export function canon(name: string): string {
  const n = norm(name);
  return ALIASES[n] ?? n;
}

// canon(EN) → RU
const EN_TO_RU: Record<string, string> = Object.fromEntries(
  Object.entries(TEAMS).map(([ru, t]) => [canon(t.en), ru])
);

/** Resolve an API-Football team name to the Russian name used in the sheet. */
export function ruFromApi(apiName: string): string | null {
  return EN_TO_RU[canon(apiName)] ?? null;
}
export function flagOf(ru: string): string {
  return TEAMS[ru]?.flag ?? "";
}
export function groupOf(ru: string): string {
  return TEAMS[ru]?.group ?? "";
}
