// Generate src/lib/teams.ts — RU↔EN team map + flag codes + canon() that
// mirrors the user's Apps Script normalization. Sources: scripts/generate.mjs
// (RU→flag, group) + live Google Sheet "Справочник" (RU↔EN). Run once / when teams change.
import { readFileSync, writeFileSync } from "node:fs";
import * as XLSX from "xlsx";

// --- RU -> {flag, group} from generate.mjs GROUPS literal ---
// RU spellings differ slightly between sheet and generate.mjs (Ю.Корея vs
// Ю. Корея, ' vs ’) — match on a punctuation/space-stripped key.
const normRu = (s) => String(s).toLowerCase().replace(/[\s.\-’'`]/g, "");
const gen = readFileSync(new URL("./generate.mjs", import.meta.url), "utf8");
const ruMeta = {};
for (const line of gen.split("\n")) {
  const m = line.match(/^\s*([A-L]):\s*\[(.+)\],?\s*$/);
  if (!m) continue;
  const letter = m[1];
  for (const t of m[2].matchAll(/\["([^"]+)","([^"]+)",/g)) ruMeta[normRu(t[1])] = { flag: t[2], group: letter };
}

// --- RU <-> EN from Справочник ---
const SID = "10V3MLlNwVz1K1VCweE1eJz02HZLbOkZUG-sSqGfqgL4";
const sx = await fetch(`https://docs.google.com/spreadsheets/d/${SID}/export?format=xlsx`);
const wb = XLSX.read(Buffer.from(await sx.arrayBuffer()), { type: "buffer" });
const ws = wb.Sheets["Справочник"];
const ref = XLSX.utils.sheet_to_json(ws, { header: 1, defval: "" });
const ruToEn = {};
for (const r of ref) if (r[0] && r[1]) ruToEn[String(r[0]).trim()] = String(r[1]).trim();

const missing = Object.keys(ruToEn).filter((ru) => !ruMeta[normRu(ru)]);
if (missing.length) console.warn("⚠ no flag for:", missing.join(", "));

const TEAMS = {};
for (const [ru, en] of Object.entries(ruToEn)) {
  const meta = ruMeta[normRu(ru)];
  TEAMS[ru] = { en, flag: meta?.flag ?? "", group: meta?.group ?? "" };
}

const out = `// AUTO-GENERATED by scripts/gen-teams.mjs — do not edit by hand.
// RU↔EN team map (from "Справочник") + flag codes (from generate.mjs).
// canon()/ALIASES mirror the Apps Script that fills the sheet, so the site and
// the sheet resolve API-Football names identically.

export type TeamInfo = { en: string; flag: string; group: string };

export const TEAMS: Record<string, TeamInfo> = ${JSON.stringify(TEAMS, null, 2)};

// API-Football spelling variants → canonical normalized form
const ALIASES: Record<string, string> = {
  turkiye: "turkey",
  czechia: "czechrepublic",
  korearepublic: "southkorea",
  capeverde: "capeverdeislands",
  drcongo: "congodr",
  congodemocraticrepublic: "congodr",
  bosniaherzegovina: "bosniaandherzegovina",
  cotedivoire: "ivorycoast",
  unitedstates: "usa",
};

export function norm(s: string): string {
  return String(s || "").toLowerCase()
    .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]/g, "");
}
export function canon(name: string): string {
  const n = norm(name);
  return ALIASES[n] ?? n;
}

// canon(EN) → RU
const EN_TO_RU: Record<string, string> = Object.fromEntries(
  Object.entries(TEAMS).map(([ru, t]) => [canon(t.en), ru])
);

/** Resolve an API-Football team name to the Russian name used in the sheet. */
export function ruFromApi(apiName: string): string | null {
  return EN_TO_RU[canon(apiName)] ?? null;
}
export function flagOf(ru: string): string {
  return TEAMS[ru]?.flag ?? "";
}
export function groupOf(ru: string): string {
  return TEAMS[ru]?.group ?? "";
}
`;
writeFileSync(new URL("../src/lib/teams.ts", import.meta.url), out);
console.log(`✓ src/lib/teams.ts — ${Object.keys(TEAMS).length} teams`);
